<?php

namespace backend\models;

use Yii;
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * This is the model class for table "oms_link".
 *
 * @property int $id
 * @property string $title
 * @property string $link
 * @property int $order
 * @property int $publish
 */
class OmsLink extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'oms_link';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'link'], 'string'],
            [['order', 'publish'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'link' => 'Документ',
            'order' => 'Сортировка',
            'publish' => 'Публикация',
        ];
    }

    public function saveDocument($fileName)
    {
        $this->link = $fileName;
        return $this->save(false);
    }

    public function getDocumentLink()
    {
        return ($this->link)
            ? '/uploads/documents/' . $this->link
            : 'Не загружен';
    }

    public function deleteDocument()
    {
        $imageUploadModel = new DocumentUpload();

        $imageUploadModel->deleteCurrentDocument($this->link);
    }

    public function beforeDelete()
    {
        $this->deleteDocument();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

}
