<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "registration".
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $tel
 * @property int $insurance
 * @property int $date
 * @property int $viewed
 */
class Registration extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'registration';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'email', 'tel', 'insurance'], 'required'],
            [['insurance', 'name', 'email'], 'string'],
            [['date', 'viewed'], 'integer'],
            [['insurance'], 'string', 'max' => 19],
            [['tel'], 'string', 'max' => 18],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'email' => 'Email',
            'tel' => 'Телефон',
            'insurance' => 'Номер полиса',
            'date' => 'Дата',
            'viewed' => 'Viewed',
        ];
    }

    public function beforeSave($insert)
    {
        $this->date =
            $this->date
                ? $this->date
                : time();

        $this->insurance = (integer) str_replace(' ', '', $this->insurance);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
